//------------------------------------------------------------------------------
// <auto-generated>
//     This code was auto-generated by com.unity.inputsystem:InputActionCodeGenerator
//     version 1.14.2
//     from Assets/Controls.inputactions
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections;
using System.Collections.Generic;
using UnityEngine.InputSystem;
using UnityEngine.InputSystem.Utilities;

/// <summary>
/// Provides programmatic access to <see cref="InputActionAsset" />, <see cref="InputActionMap" />, <see cref="InputAction" /> and <see cref="InputControlScheme" /> instances defined in asset "Assets/Controls.inputactions".
/// </summary>
/// <remarks>
/// This class is source generated and any manual edits will be discarded if the associated asset is reimported or modified.
/// </remarks>
/// <example>
/// <code>
/// using namespace UnityEngine;
/// using UnityEngine.InputSystem;
///
/// // Example of using an InputActionMap named "Player" from a UnityEngine.MonoBehaviour implementing callback interface.
/// public class Example : MonoBehaviour, MyActions.IPlayerActions
/// {
///     private MyActions_Actions m_Actions;                  // Source code representation of asset.
///     private MyActions_Actions.PlayerActions m_Player;     // Source code representation of action map.
///
///     void Awake()
///     {
///         m_Actions = new MyActions_Actions();              // Create asset object.
///         m_Player = m_Actions.Player;                      // Extract action map object.
///         m_Player.AddCallbacks(this);                      // Register callback interface IPlayerActions.
///     }
///
///     void OnDestroy()
///     {
///         m_Actions.Dispose();                              // Destroy asset object.
///     }
///
///     void OnEnable()
///     {
///         m_Player.Enable();                                // Enable all actions within map.
///     }
///
///     void OnDisable()
///     {
///         m_Player.Disable();                               // Disable all actions within map.
///     }
///
///     #region Interface implementation of MyActions.IPlayerActions
///
///     // Invoked when "Move" action is either started, performed or canceled.
///     public void OnMove(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnMove: {context.ReadValue&lt;Vector2&gt;()}");
///     }
///
///     // Invoked when "Attack" action is either started, performed or canceled.
///     public void OnAttack(InputAction.CallbackContext context)
///     {
///         Debug.Log($"OnAttack: {context.ReadValue&lt;float&gt;()}");
///     }
///
///     #endregion
/// }
/// </code>
/// </example>
public partial class @Controls: IInputActionCollection2, IDisposable
{
    /// <summary>
    /// Provides access to the underlying asset instance.
    /// </summary>
    public InputActionAsset asset { get; }

    /// <summary>
    /// Constructs a new instance.
    /// </summary>
    public @Controls()
    {
        asset = InputActionAsset.FromJson(@"{
    ""version"": 1,
    ""name"": ""Controls"",
    ""maps"": [
        {
            ""name"": ""Skateboard"",
            ""id"": ""8a5113cb-cf32-4ec7-9bfb-6568059d47e7"",
            ""actions"": [
                {
                    ""name"": ""Push"",
                    ""type"": ""Button"",
                    ""id"": ""016413ed-7078-454f-b806-8a5bb387e228"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""Turn"",
                    ""type"": ""Button"",
                    ""id"": ""32199b0a-085d-4acd-8e21-e57d7eae2003"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrickLeft"",
                    ""type"": ""Button"",
                    ""id"": ""fa55435d-b126-4465-8183-546eb6991142"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrickRight"",
                    ""type"": ""Button"",
                    ""id"": ""f2686c7e-2f3f-4ded-9aa2-6681a2e47cc0"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrickUp"",
                    ""type"": ""Button"",
                    ""id"": ""9b342c8c-525f-4d36-8b45-b6ed49710042"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                },
                {
                    ""name"": ""TrickDown"",
                    ""type"": ""Button"",
                    ""id"": ""eb85123d-503c-462e-8e23-f00659cda137"",
                    ""expectedControlType"": """",
                    ""processors"": """",
                    ""interactions"": """",
                    ""initialStateCheck"": false
                }
            ],
            ""bindings"": [
                {
                    ""name"": """",
                    ""id"": ""a26de8fd-0ca4-4891-b770-2c750a87b2e6"",
                    ""path"": ""<Keyboard>/space"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Push"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""1D Axis"",
                    ""id"": ""43e2a133-c391-43e2-b54e-f0da58c970af"",
                    ""path"": ""1DAxis"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": true,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": ""negative"",
                    ""id"": ""018347fb-1b9b-41d9-8875-6e11485cedff"",
                    ""path"": ""<Keyboard>/a"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": ""positive"",
                    ""id"": ""6629938a-9614-4ce7-9c73-078e1fbb8a9a"",
                    ""path"": ""<Keyboard>/d"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""Turn"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": true
                },
                {
                    ""name"": """",
                    ""id"": ""94162676-fa94-48a0-91cf-8c6e96061dd0"",
                    ""path"": ""<Keyboard>/leftArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrickLeft"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""ea307789-e998-4b96-a4c3-2823f3fede46"",
                    ""path"": ""<Keyboard>/rightArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrickRight"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""b9298b07-17ed-48d1-a41a-8d711dea7dac"",
                    ""path"": ""<Keyboard>/upArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrickUp"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                },
                {
                    ""name"": """",
                    ""id"": ""50397903-388f-4b42-9c42-1052ad070160"",
                    ""path"": ""<Keyboard>/downArrow"",
                    ""interactions"": """",
                    ""processors"": """",
                    ""groups"": """",
                    ""action"": ""TrickDown"",
                    ""isComposite"": false,
                    ""isPartOfComposite"": false
                }
            ]
        }
    ],
    ""controlSchemes"": []
}");
        // Skateboard
        m_Skateboard = asset.FindActionMap("Skateboard", throwIfNotFound: true);
        m_Skateboard_Push = m_Skateboard.FindAction("Push", throwIfNotFound: true);
        m_Skateboard_Turn = m_Skateboard.FindAction("Turn", throwIfNotFound: true);
        m_Skateboard_TrickLeft = m_Skateboard.FindAction("TrickLeft", throwIfNotFound: true);
        m_Skateboard_TrickRight = m_Skateboard.FindAction("TrickRight", throwIfNotFound: true);
        m_Skateboard_TrickUp = m_Skateboard.FindAction("TrickUp", throwIfNotFound: true);
        m_Skateboard_TrickDown = m_Skateboard.FindAction("TrickDown", throwIfNotFound: true);
    }

    ~@Controls()
    {
        UnityEngine.Debug.Assert(!m_Skateboard.enabled, "This will cause a leak and performance issues, Controls.Skateboard.Disable() has not been called.");
    }

    /// <summary>
    /// Destroys this asset and all associated <see cref="InputAction"/> instances.
    /// </summary>
    public void Dispose()
    {
        UnityEngine.Object.Destroy(asset);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindingMask" />
    public InputBinding? bindingMask
    {
        get => asset.bindingMask;
        set => asset.bindingMask = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.devices" />
    public ReadOnlyArray<InputDevice>? devices
    {
        get => asset.devices;
        set => asset.devices = value;
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.controlSchemes" />
    public ReadOnlyArray<InputControlScheme> controlSchemes => asset.controlSchemes;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Contains(InputAction)" />
    public bool Contains(InputAction action)
    {
        return asset.Contains(action);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.GetEnumerator()" />
    public IEnumerator<InputAction> GetEnumerator()
    {
        return asset.GetEnumerator();
    }

    /// <inheritdoc cref="IEnumerable.GetEnumerator()" />
    IEnumerator IEnumerable.GetEnumerator()
    {
        return GetEnumerator();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Enable()" />
    public void Enable()
    {
        asset.Enable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.Disable()" />
    public void Disable()
    {
        asset.Disable();
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.bindings" />
    public IEnumerable<InputBinding> bindings => asset.bindings;

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindAction(string, bool)" />
    public InputAction FindAction(string actionNameOrId, bool throwIfNotFound = false)
    {
        return asset.FindAction(actionNameOrId, throwIfNotFound);
    }

    /// <inheritdoc cref="UnityEngine.InputSystem.InputActionAsset.FindBinding(InputBinding, out InputAction)" />
    public int FindBinding(InputBinding bindingMask, out InputAction action)
    {
        return asset.FindBinding(bindingMask, out action);
    }

    // Skateboard
    private readonly InputActionMap m_Skateboard;
    private List<ISkateboardActions> m_SkateboardActionsCallbackInterfaces = new List<ISkateboardActions>();
    private readonly InputAction m_Skateboard_Push;
    private readonly InputAction m_Skateboard_Turn;
    private readonly InputAction m_Skateboard_TrickLeft;
    private readonly InputAction m_Skateboard_TrickRight;
    private readonly InputAction m_Skateboard_TrickUp;
    private readonly InputAction m_Skateboard_TrickDown;
    /// <summary>
    /// Provides access to input actions defined in input action map "Skateboard".
    /// </summary>
    public struct SkateboardActions
    {
        private @Controls m_Wrapper;

        /// <summary>
        /// Construct a new instance of the input action map wrapper class.
        /// </summary>
        public SkateboardActions(@Controls wrapper) { m_Wrapper = wrapper; }
        /// <summary>
        /// Provides access to the underlying input action "Skateboard/Push".
        /// </summary>
        public InputAction @Push => m_Wrapper.m_Skateboard_Push;
        /// <summary>
        /// Provides access to the underlying input action "Skateboard/Turn".
        /// </summary>
        public InputAction @Turn => m_Wrapper.m_Skateboard_Turn;
        /// <summary>
        /// Provides access to the underlying input action "Skateboard/TrickLeft".
        /// </summary>
        public InputAction @TrickLeft => m_Wrapper.m_Skateboard_TrickLeft;
        /// <summary>
        /// Provides access to the underlying input action "Skateboard/TrickRight".
        /// </summary>
        public InputAction @TrickRight => m_Wrapper.m_Skateboard_TrickRight;
        /// <summary>
        /// Provides access to the underlying input action "Skateboard/TrickUp".
        /// </summary>
        public InputAction @TrickUp => m_Wrapper.m_Skateboard_TrickUp;
        /// <summary>
        /// Provides access to the underlying input action "Skateboard/TrickDown".
        /// </summary>
        public InputAction @TrickDown => m_Wrapper.m_Skateboard_TrickDown;
        /// <summary>
        /// Provides access to the underlying input action map instance.
        /// </summary>
        public InputActionMap Get() { return m_Wrapper.m_Skateboard; }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Enable()" />
        public void Enable() { Get().Enable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.Disable()" />
        public void Disable() { Get().Disable(); }
        /// <inheritdoc cref="UnityEngine.InputSystem.InputActionMap.enabled" />
        public bool enabled => Get().enabled;
        /// <summary>
        /// Implicitly converts an <see ref="SkateboardActions" /> to an <see ref="InputActionMap" /> instance.
        /// </summary>
        public static implicit operator InputActionMap(SkateboardActions set) { return set.Get(); }
        /// <summary>
        /// Adds <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <param name="instance">Callback instance.</param>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c> or <paramref name="instance"/> have already been added this method does nothing.
        /// </remarks>
        /// <seealso cref="SkateboardActions" />
        public void AddCallbacks(ISkateboardActions instance)
        {
            if (instance == null || m_Wrapper.m_SkateboardActionsCallbackInterfaces.Contains(instance)) return;
            m_Wrapper.m_SkateboardActionsCallbackInterfaces.Add(instance);
            @Push.started += instance.OnPush;
            @Push.performed += instance.OnPush;
            @Push.canceled += instance.OnPush;
            @Turn.started += instance.OnTurn;
            @Turn.performed += instance.OnTurn;
            @Turn.canceled += instance.OnTurn;
            @TrickLeft.started += instance.OnTrickLeft;
            @TrickLeft.performed += instance.OnTrickLeft;
            @TrickLeft.canceled += instance.OnTrickLeft;
            @TrickRight.started += instance.OnTrickRight;
            @TrickRight.performed += instance.OnTrickRight;
            @TrickRight.canceled += instance.OnTrickRight;
            @TrickUp.started += instance.OnTrickUp;
            @TrickUp.performed += instance.OnTrickUp;
            @TrickUp.canceled += instance.OnTrickUp;
            @TrickDown.started += instance.OnTrickDown;
            @TrickDown.performed += instance.OnTrickDown;
            @TrickDown.canceled += instance.OnTrickDown;
        }

        /// <summary>
        /// Removes <see cref="InputAction.started"/>, <see cref="InputAction.performed"/> and <see cref="InputAction.canceled"/> callbacks provided via <param cref="instance" /> on all input actions contained in this map.
        /// </summary>
        /// <remarks>
        /// Calling this method when <paramref name="instance" /> have not previously been registered has no side-effects.
        /// </remarks>
        /// <seealso cref="SkateboardActions" />
        private void UnregisterCallbacks(ISkateboardActions instance)
        {
            @Push.started -= instance.OnPush;
            @Push.performed -= instance.OnPush;
            @Push.canceled -= instance.OnPush;
            @Turn.started -= instance.OnTurn;
            @Turn.performed -= instance.OnTurn;
            @Turn.canceled -= instance.OnTurn;
            @TrickLeft.started -= instance.OnTrickLeft;
            @TrickLeft.performed -= instance.OnTrickLeft;
            @TrickLeft.canceled -= instance.OnTrickLeft;
            @TrickRight.started -= instance.OnTrickRight;
            @TrickRight.performed -= instance.OnTrickRight;
            @TrickRight.canceled -= instance.OnTrickRight;
            @TrickUp.started -= instance.OnTrickUp;
            @TrickUp.performed -= instance.OnTrickUp;
            @TrickUp.canceled -= instance.OnTrickUp;
            @TrickDown.started -= instance.OnTrickDown;
            @TrickDown.performed -= instance.OnTrickDown;
            @TrickDown.canceled -= instance.OnTrickDown;
        }

        /// <summary>
        /// Unregisters <param cref="instance" /> and unregisters all input action callbacks via <see cref="SkateboardActions.UnregisterCallbacks(ISkateboardActions)" />.
        /// </summary>
        /// <seealso cref="SkateboardActions.UnregisterCallbacks(ISkateboardActions)" />
        public void RemoveCallbacks(ISkateboardActions instance)
        {
            if (m_Wrapper.m_SkateboardActionsCallbackInterfaces.Remove(instance))
                UnregisterCallbacks(instance);
        }

        /// <summary>
        /// Replaces all existing callback instances and previously registered input action callbacks associated with them with callbacks provided via <param cref="instance" />.
        /// </summary>
        /// <remarks>
        /// If <paramref name="instance" /> is <c>null</c>, calling this method will only unregister all existing callbacks but not register any new callbacks.
        /// </remarks>
        /// <seealso cref="SkateboardActions.AddCallbacks(ISkateboardActions)" />
        /// <seealso cref="SkateboardActions.RemoveCallbacks(ISkateboardActions)" />
        /// <seealso cref="SkateboardActions.UnregisterCallbacks(ISkateboardActions)" />
        public void SetCallbacks(ISkateboardActions instance)
        {
            foreach (var item in m_Wrapper.m_SkateboardActionsCallbackInterfaces)
                UnregisterCallbacks(item);
            m_Wrapper.m_SkateboardActionsCallbackInterfaces.Clear();
            AddCallbacks(instance);
        }
    }
    /// <summary>
    /// Provides a new <see cref="SkateboardActions" /> instance referencing this action map.
    /// </summary>
    public SkateboardActions @Skateboard => new SkateboardActions(this);
    /// <summary>
    /// Interface to implement callback methods for all input action callbacks associated with input actions defined by "Skateboard" which allows adding and removing callbacks.
    /// </summary>
    /// <seealso cref="SkateboardActions.AddCallbacks(ISkateboardActions)" />
    /// <seealso cref="SkateboardActions.RemoveCallbacks(ISkateboardActions)" />
    public interface ISkateboardActions
    {
        /// <summary>
        /// Method invoked when associated input action "Push" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnPush(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "Turn" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTurn(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TrickLeft" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTrickLeft(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TrickRight" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTrickRight(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TrickUp" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTrickUp(InputAction.CallbackContext context);
        /// <summary>
        /// Method invoked when associated input action "TrickDown" is either <see cref="UnityEngine.InputSystem.InputAction.started" />, <see cref="UnityEngine.InputSystem.InputAction.performed" /> or <see cref="UnityEngine.InputSystem.InputAction.canceled" />.
        /// </summary>
        /// <seealso cref="UnityEngine.InputSystem.InputAction.started" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.performed" />
        /// <seealso cref="UnityEngine.InputSystem.InputAction.canceled" />
        void OnTrickDown(InputAction.CallbackContext context);
    }
}
